apiVersion: v1
kind: Service
metadata:
  name: kibana-external
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 30601
  selector:
    app: kibana
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-internal
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
    targetPort: 5601
  selector:
    app: kibana
